esphome:
    name: ikea
esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0


wifi:
  ssid: 
  password: 

# Enable logging
logger:
  level: info

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

web_server:
  port: 80
  ota: false

uart:
  rx_pin: GPIO17
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "PM 2.5 Concentration"

